// <auto-generated />
using MarkWebPrintShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarkWebPrintShop.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260110134202_AddServicesToDB")]
    partial class AddServicesToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarkWebPrintShop.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.HasKey("ServiceId")
                        .HasName("pk_services");

                    b.ToTable("services", (string)null);

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            Description = "We handle all print jobs, from personal assignments and government requirements to corporate documents, accepting only PDF and Word file formats. Simply upload your documents to our portal, select your printing options, and pick up your crisp, clear prints at your convenience.",
                            IsAvailable = true,
                            ServiceName = "Document Printing"
                        },
                        new
                        {
                            ServiceId = 2,
                            Description = "Our high-speed photocopy services specialize in handling sensitive official documents, including all government and corporate requirements. We guarantee crisp, compliant reproductions on demand, with bulk services available for large volume needs.",
                            IsAvailable = true,
                            ServiceName = "Photo Copy/Xerox"
                        },
                        new
                        {
                            ServiceId = 3,
                            Description = "Develop photos straight from your smartphone in minutes using our seamless online photo portal. We offer a range of sizes and finishes to ensure your digital memories are captured with exceptional color clarity and quality.",
                            IsAvailable = true,
                            ServiceName = "Photo Develop"
                        },
                        new
                        {
                            ServiceId = 4,
                            Description = "We provide fast and accurate printing services for government and corporate ID photos, offering common dimensions like 1x1, 2x2, and passport sizes. Upload your image to receive a perfectly sized sheet of photos that meet all official specifications.",
                            IsAvailable = true,
                            ServiceName = "Photo ID"
                        },
                        new
                        {
                            ServiceId = 5,
                            Description = "We offer secure plastic lamination services ideal for government IDs, licenses, and official documents that require protection. Ensure your essential paperwork is sealed, secure, and resilient against spills or bending.",
                            IsAvailable = true,
                            ServiceName = "Lamination"
                        },
                        new
                        {
                            ServiceId = 6,
                            Description = "We offer plastic lamination services ideal for government IDs, licenses, and official documents that require protection. Ensure your essential paperwork is sealed, secure, and resilient against spills or bending.",
                            IsAvailable = true,
                            ServiceName = "Lamination"
                        },
                        new
                        {
                            ServiceId = 7,
                            Description = "Land your next job with a professional, tailored resume or Curriculum Vitae (CV) created by our experts. We design clean, impactful documents that highlight your experience and help you stand out to employers.",
                            IsAvailable = true,
                            ServiceName = "Resume Writing Services"
                        },
                        new
                        {
                            ServiceId = 8,
                            Description = "Utilize our graphic design expertise for all your digital needs, creating professional logos, infographics, and custom graphics using the Canva platform. We bring your vision to life with modern, engaging designs tailored specifically for your brand or project.",
                            IsAvailable = true,
                            ServiceName = "Graphic Design Services"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
